PULL_REQUEST_TEMPLATE.md
app/controllers/api/v1/clients_controller.rb
config/routes.rb
spec/requests/api/v1/client_creation_spec.rb

This functionality allows a client to make a post request and create a new client profile.
​
Happy and sad path testing for creating a new client
​Added route api/v1/clients (with params for a new client)
Params must have a unique name and email, or a 404 will be returned
​
​I originally started sending the new client information in the body of the request, but then decided to use strong params in the controller, and send the info in the request params.
​
​
​
- [ x] My code has no unused/commented out code
- [x ] I have reviewed my code
- [x
] I have fully tested my code
​
* This was helpful to see if a resource exists in active record
https://apidock.com/rails/ActiveRecord/Base/exists%3f/class

Client profile creation

---

app/controllers/api/v1/clients_controller.rb
config/routes.rb
spec/requests/api/v1/client_update_spec.rb

closes  # 'Client Update Endpoint'
​
Added ​Happy/sad path tests for updating a clients profile
Added Route to clients#update action
​Added Update action to clients controller (with conditional for unique email and username)
​
​

Client profile update

---

app/controllers/api/v1/clients_controller.rb
config/routes.rb
spec/requests/api/v1/client_delete_spec.rb

closes # Client Delete Endpoint
​
Added ​Happy/sad path tests for deleting a clients profile
Added Route to clients#destroy action
​Added Destroy action to clients controller (with conditional for valid ID)
​
​

Client profile delete

---

README.md

Co-Authored-By: Noah Flint <34421236+n-flint@users.noreply.github.com>
​
​- updates readme with client endpoints:
- DELETE
- UPDATE
- CREATE
- READ
​
​

update readme with client endpoints

---

app/controllers/api/v1/lists_controller.rb
app/models/client.rb
app/models/list.rb
config/routes.rb
db/migrate/20190903211700_create_lists.rb
db/schema.rb
spec/models/client_spec.rb
spec/models/list_spec.rb
spec/requests/api/v1/lists/list_creation_spec.rb

List Creation
​Client can create a new list, if they provide a valid client ID. This list must have a name. If a invalid ID is provided, a 404 will be returned
​
​

Lists creation

---

README.md
app/controllers/api/v1/clients_controller.rb
app/controllers/api/v1/lists_controller.rb
app/serializers/client_serializer.rb
spec/requests/api/v1/client_creation_spec.rb
spec/requests/api/v1/client_spec.rb
spec/requests/api/v1/client_update_spec.rb

​
​- Changes client attributes to arrays:
- needs
- medications
​  - allergies 
- Updates readme with new client changes and adds list endpoint documentation
​
​

Fe requests1

---

app/controllers/api/v1/tasks_controller.rb
app/models/task.rb
config/routes.rb
db/migrate/20190904235439_create_tasks.rb
db/migrate/20190905170807_add_due_date_to_tasks.rb
db/schema.rb
spec/models/task_spec.rb
spec/requests/api/v1/tasks/task_creation_spec.rb

User can make a POST request to create a new task
​POST "/api/v1/clients/:id/lists/:list_id/tasks"
User must provide a valid client id and valid list id
User must provide a name for the new task
​
​Testing for datetime for a new task. Ended up just testing for the presence of a due_date key.
​
​
​
​
Link talking about the differences between date, time, datetime and timestamps
https://nandovieira.com/working-with-dates-on-ruby-on-rails

Task creation

---

Gemfile
Gemfile.lock
README.md
app/controllers/api/v1/clients_controller.rb
app/models/client.rb
app/serializers/client_serializer.rb
db/migrate/20190905045330_add_pass_and_diet_to_clients.rb
db/schema.rb
spec/factories/client_factory.rb
spec/requests/api/v1/client_creation_spec.rb
spec/requests/api/v1/client_delete_spec.rb
spec/requests/api/v1/client_spec.rb
spec/requests/api/v1/client_update_spec.rb

closes Trello cards: 
- Add Password to Clients
- Add diet_restrictions attribute to Clients
​
​- Adds to client attributes:
- password_digest - string
- diet_restrictions - string
- Adds bcrypt gem 
- Changes client factory to account for new attributes
- Changes all client request spec to account for new attributes
- Updates endpoint readme documentation for new client attributes
​
​
​Figuring out how paramsWrapper was manipulating incoming json to not allow "password" or "password_confirmation" through strong params
​
​
​
* Resource link AND small description of info gathered/learned
https://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html - This is where I learned how to change the paramsWrapper to include attributes that weren't part of the Client …

Adding atts to client

---

README.md
app/controllers/api/v1/lists_controller.rb
config/routes.rb
spec/factories/list_factory.rb
spec/factories/task_factory.rb
spec/requests/api/v1/lists/list_index_spec.rb

closes Trello cards: 
1. Client Lists Tasks Index Endpoint
​
​- Adds factories:  (No relationships created yet)
- tasks
- lists
- Adds tests for client lists index endpoint
- Adds endpoint to get all client lists (and docs to readme)
​
​
​
* Resource link AND small description of info gathered/learned

Client list index

---

README.md
app/controllers/api/v1/lists_controller.rb
config/routes.rb
spec/factories/list_factory.rb
spec/factories/task_factory.rb
spec/requests/api/v1/lists/list_index_spec.rb
spec/requests/api/v1/lists/list_update_spec.rb

closes Trello cards: 
- Client Lists Tasks Update Endpoint
​
​- Adds tests and functionality for updating a clients list
​
​

Client list update

---

README.md

This PR adds documentation to the README.md for two endpoints:
- List Task Creation Endpoint
- List Deletion Endpoint

Readme endpoints update

---

app/controllers/api/v1/clients_controller.rb
app/models/client.rb
spec/models/client_spec.rb

Refactors the update action in the clients controller
​
​Took the conditionals for updating the params for needs, diet_restrictions, medications and allergies, moved them to a helper method called custom_needs, in the client.rb file
​
​

Client update method refactor

---

README.md
app/controllers/api/v1/tasks_controller.rb
config/routes.rb
spec/requests/api/v1/tasks/task_update_spec.rb

closes Trello Cards:
- Client Lists Tasks Update Endpoint
​
​- Adds tests for updated a task with sad paths
- Adds endpoint to update a task on a clients list
- Updates readme with task update endpoint details
​
​

Task update endpoint

---

README.md
app/controllers/api/v1/tasks_controller.rb
config/routes.rb
spec/requests/api/v1/tasks/task_delete_spec.rb
spec/requests/api/v1/tasks/task_update_spec.rb

closes Trello Cards: 
- Client Lists Tasks Delete Endpoint
​
​- Adds tests for deleting a task with sad paths
- Adds endpoint to delete a task
- Adds endpoint details to readme
​

Task delete endpoint

---

app/controllers/api/v1/tasks_controller.rb
app/models/client.rb
db/seeds.rb
spec/requests/api/v1/lists/list_creation_spec.rb

​- Adds protect_from_forgery method to tasks controller to allow requests from outside app
- Adds dependency destroying of client lists
- Seeds the db with a test client for front end testing
​
​

Lists index fix

---

README.md

- Adds to list update endpoint documentation in readme:
- Request body description

Add body description to list update endpoint documentation

---

app/controllers/api/v1/clients_controller.rb
app/serializers/client_serializer.rb
spec/requests/api/v1/clients/client_creation_spec.rb

​
​- Adds password to return when creating a client per front end request
​
​

Add password to return from creating a Client for front end login

---

README.md
app/controllers/api/v1/tasks_controller.rb
app/serializers/task_serializer.rb
db/seeds.rb
spec/factories/task_factory.rb
spec/requests/api/v1/tasks/task_creation_spec.rb
spec/requests/api/v1/tasks/task_index_spec.rb
spec/requests/api/v1/tasks/task_update_spec.rb

- Changes json responses with due date to format requested ("mm/dd")
**Description**
- Changes task factory to use tomorrows date
- Adds task serializer
- Changes tasks controller to use serializer
- Changes task date to requested format in task serializer
- Adds optional due date directions to task creation in readme
​
​

Fe requests3

---

app/controllers/api/v1/caretakers_controller.rb
app/models/caretaker.rb
config/routes.rb
db/migrate/20190910023749_create_caretakers.rb
db/migrate/20190910155316_add_caretakers_to_lists.rb
db/schema.rb
spec/models/caretaker_spec.rb
spec/requests/api/v1/caretakers/caretaker_creation_spec.rb
spec/requests/api/v1/clients/client_creation_spec.rb

Caretaker Profile Creation
​
A caretaker can create an account with the following params:
- username (must be unique)
- name
- email (must be unique)
- password
- password_confirmation
- phone number
Tests for happy path and sad path
- returns a 201 with a valid request
- returns a 400 if a non-unique username is provided
​- returns a 400 if a non-unique email is provided
​
​

Caretaker profile creation

---

app/controllers/api/v1/caretakers_controller.rb
config/routes.rb
spec/requests/api/v1/caretakers/caretaker_update_spec.rb

User can update a caretakers profile information
​
​Created endpoint to update a caretakers profile
User must provide a valid caretaker ID
If updating the username or email, the updated data must be unique
​
​Sad path testing for unique username/email and valid ID
​
​
​

Caretaker profile update

---

README.md
app/controllers/api/v1/caretakers_controller.rb
config/routes.rb
spec/requests/api/v1/caretakers/caretaker_deletion_spec.rb

User can delete a caretakers profile
​
​User can delete a caretakers profile by providing a valid caretaker ID
If an invalid ID is provided, a 404 will be returned
​

Caretaker deletion

---

app/controllers/api/v1/caretakers_controller.rb
config/routes.rb
spec/requests/api/v1/caretakers/caretaker_index_spec.rb

User can see all the caretakers in the database
​
When a user makes a GET request to '/api/v1/caretakers', a list of all the caretakers is returned
​
​

Caretakers index

---

README.md
app/controllers/api/v1/caretakers_controller.rb
config/routes.rb
spec/requests/api/v1/caretakers/caretaker_show_spec.rb

User can find a caretaker by the ID
User can make a GET request to '/api/v1/caretakers/:id' to receive a specific client
if an invalid ID is provided, a 404 will be returned
Added documentation to README for a list of all the caretakers, and a single caretaker
​
​

Caretaker show

---

README.md
spec/services/google_service_spec.rb

- Adds to readme:
- Adds 'role' attribute to all client and caretaker docs
- Checks general caretaker readme docs for accuracy

Caretaker readme accuracy

---

app/controllers/api/v1/login_controller.rb
spec/requests/api/v1/caretakers/caretaker_login_spec.rb

closes Trello Cards:
- Change login endpoint to accept caretakers
​
​- Adds tests for logging in a caretaker
- Changes login controller to accept and return json for caretakers
​
​
​
* Resource link AND small description of info gathered/learned

Caretaker login

---

README.md

Refactored README.md endpoints
Added challenges and success endpoints
Added database schema screenshot
Added production with link to Heroku site
​
- Video about adding images to a github README
- https://www.youtube.com/watch?v=nvPOUdz5PL4

Readme finalize
